In [53]:
from transformers import T5Tokenizer, T5Model
from gluonnlp.data.tokenizers import SentencepieceTokenizer
from gluonnlp.data.vocab import Vocab

In [31]:
trans = T5Tokenizer.from_pretrained("t5-base")

In [36]:
import os
import tempfile
from gluonnnlp.
from gluonnlp.utils.misc import download

with tempfile.TemporaryDirectory() as dir_path: 
    vocab_path = os.path.join(dir_path, 'spm.model')
    download(
        url='https://huggingface.co/t5-base/resolve/main/spiece.model', 
        path=vocab_path
    )
    spm = SentencepieceTokenizer(vocab_path)
    os.remove(vocab_path)

100%|██████████| 792k/792k [00:00<00:00, 1.82MiB/s]


In [10]:
tr = T5Tokenizer(trans.vocab_file, extra_ids=200)

In [52]:
spm

SentencepieceTokenizer(
   model_path = /tmp/tmp3ajlomgf/spm.model
   lowercase = False, nbest = 0, alpha = 0.0
   vocab = Vocab(size=32000, unk_token="<unk>", pad_token="<pad>", eos_token="</s>")
)

In [40]:
spm.vocab.all_tokens

['<pad>',
 '</s>',
 '<unk>',
 '▁',
 'X',
 '.',
 ',',
 's',
 '▁the',
 'a',
 ':',
 '▁and',
 '▁to',
 '▁of',
 '▁fill',
 'e',
 '▁in',
 't',
 '-',
 '▁is',
 '▁de',
 '▁for',
 '’',
 'i',
 '▁that',
 '▁you',
 'd',
 '▁I',
 '▁with',
 'n',
 '▁on',
 "'",
 'o',
 '▁are',
 '▁it',
 'en',
 '▁be',
 '▁The',
 '▁as',
 '▁your',
 'l',
 '▁(',
 '▁or',
 '▁have',
 '▁at',
 '▁from',
 '▁an',
 '▁was',
 '▁this',
 'er',
 '▁la',
 'm',
 'r',
 'ing',
 '▁can',
 '!',
 '▁will',
 '▁by',
 '?',
 '▁not',
 're',
 ')',
 '▁we',
 'y',
 '▁und',
 '▁has',
 '▁all',
 '▁die',
 '▁but',
 '▁our',
 '▁their',
 '▁A',
 '▁more',
 '▁un',
 '▁der',
 'c',
 'u',
 'in',
 '▁so',
 '▁they',
 '▁one',
 '▁about',
 '▁my',
 'ul',
 '▁which',
 'à',
 '▁In',
 '/',
 'he',
 'f',
 '▁le',
 '▁out',
 '▁also',
 '▁des',
 '▁It',
 '▁up',
 '▁"',
 '▁time',
 'ă',
 'if',
 '▁This',
 '▁We',
 'p',
 '▁do',
 '–',
 '▁“',
 'on',
 'h',
 '▁si',
 'le',
 '▁les',
 '▁în',
 '▁his',
 '▁who',
 '▁like',
 'b',
 '▁when',
 ';',
 '▁been',
 '▁other',
 'ly',
 '"',
 'g',
 '▁cu',
 '▁care',
 '▁what',
 '▁n

In [3]:
# import math

# extra_ids = 100
# id_len = math.ceil(math.log(extra_ids, 10))
special_tokens = {'extra_{}_token'.format(str(i).zfill(id_len)): '<extra_id_{}>'.format(str(i).zfill(id_len)) for i in range(extra_ids)}
special_tokens['eos_token'] = '</s>'
special_tokens['unk_token'] = '<unk>'
special_tokens['pad_token'] = '<pad>'
# # gluon = SentencepieceTokenizer(
# #     vocab=Vocab(trans.get_vocab(), **special_tokens)
# # )

In [9]:
trans._extra_ids

100

In [10]:
trans.get_vocab()

{'<pad>': 0,
 '</s>': 1,
 '<unk>': 2,
 '▁': 3,
 'X': 4,
 '.': 5,
 ',': 6,
 's': 7,
 '▁the': 8,
 'a': 9,
 ':': 10,
 '▁and': 11,
 '▁to': 12,
 '▁of': 13,
 '▁fill': 14,
 'e': 15,
 '▁in': 16,
 't': 17,
 '-': 18,
 '▁is': 19,
 '▁de': 20,
 '▁for': 21,
 '’': 22,
 'i': 23,
 '▁that': 24,
 '▁you': 25,
 'd': 26,
 '▁I': 27,
 '▁with': 28,
 'n': 29,
 '▁on': 30,
 "'": 31,
 'o': 32,
 '▁are': 33,
 '▁it': 34,
 'en': 35,
 '▁be': 36,
 '▁The': 37,
 '▁as': 38,
 '▁your': 39,
 'l': 40,
 '▁(': 41,
 '▁or': 42,
 '▁have': 43,
 '▁at': 44,
 '▁from': 45,
 '▁an': 46,
 '▁was': 47,
 '▁this': 48,
 'er': 49,
 '▁la': 50,
 'm': 51,
 'r': 52,
 'ing': 53,
 '▁can': 54,
 '!': 55,
 '▁will': 56,
 '▁by': 57,
 '?': 58,
 '▁not': 59,
 're': 60,
 ')': 61,
 '▁we': 62,
 'y': 63,
 '▁und': 64,
 '▁has': 65,
 '▁all': 66,
 '▁die': 67,
 '▁but': 68,
 '▁our': 69,
 '▁their': 70,
 '▁A': 71,
 '▁more': 72,
 '▁un': 73,
 '▁der': 74,
 'c': 75,
 'u': 76,
 'in': 77,
 '▁so': 78,
 '▁they': 79,
 '▁one': 80,
 '▁about': 81,
 '▁my': 82,
 'ul': 83,
 '▁which': 8

In [5]:
# list(trans.get_vocab().keys())

# trans.pad_token
# trans.eos_token
# trans.unk_token

In [32]:
extra_ids = trans._extra_ids
do_lower = False

special_tokens = {'extra{}_token'.format(i): '<extra_id_{}>'.format(i) for i in range(extra_ids - 1, -1, -1)}
special_tokens['eos_token'] = trans.eos_token
special_tokens['unk_token'] = trans.unk_token
special_tokens['pad_token'] = trans.pad_token

tokenizer = SentencepieceTokenizer(
    model_path=trans.vocab_file, 
    vocab=Vocab(list(trans.get_vocab().keys()), **special_tokens), 
    lowercase=do_lower
)

In [33]:
tokenizer

SentencepieceTokenizer(
   model_path = /home/ubuntu/.cache/huggingface/transformers/684a47ca6257e4ca71f0037771464c5b323e945fbc58697d2fad8a7dd1a2f8ba.3b69006860e7b5d0a63ffdddc01ddcd6b7c318a6f4fd793596552c741734c62d
   lowercase = False, nbest = 0, alpha = 0.0
   vocab = Vocab(size=32100, unk_token="<unk>", pad_token="<pad>", eos_token="</s>", extra99_token="<extra_id_99>", extra98_token="<extra_id_98>", extra97_token="<extra_id_97>", extra96_token="<extra_id_96>", extra95_token="<extra_id_95>", extra94_token="<extra_id_94>", extra93_token="<extra_id_93>", extra92_token="<extra_id_92>", extra91_token="<extra_id_91>", extra90_token="<extra_id_90>", extra89_token="<extra_id_89>", extra88_token="<extra_id_88>", extra87_token="<extra_id_87>", extra86_token="<extra_id_86>", extra85_token="<extra_id_85>", extra84_token="<extra_id_84>", extra83_token="<extra_id_83>", extra82_token="<extra_id_82>", extra81_token="<extra_id_81>", extra80_token="<extra_id_80>", extra79_token="<extra_id_79>", extr

In [17]:
import tempfile
import os

from gluonnlp.base import get_repo_url
from gluonnlp.data import load_vocab
from gluonnlp.utils.misc import download

100%|██████████| 792k/792k [00:00<00:00, 11.7MiB/s]
100%|██████████| 476k/476k [00:00<00:00, 8.02MiB/s]Downloading /tmp/tmpptcvki94/t5_spm.model from s3://gluonnlp-numpy-data/tokenizer_test_models/sentencepiece/case_t5/test_t5spm-5f05e7.model...

['<pad>', '</s>', '<unk>', '<extra_id_99>', '<extra_id_98>', '<extra_id_97>', '<extra_id_96>', '<extra_id_95>', '<extra_id_94>', '<extra_id_93>', '<extra_id_92>', '<extra_id_91>', '<extra_id_90>', '<extra_id_89>', '<extra_id_88>', '<extra_id_87>', '<extra_id_86>', '<extra_id_85>', '<extra_id_84>', '<extra_id_83>', '<extra_id_82>', '<extra_id_81>', '<extra_id_80>', '<extra_id_79>', '<extra_id_78>', '<extra_id_77>', '<extra_id_76>', '<extra_id_75>', '<extra_id_74>', '<extra_id_73>', '<extra_id_72>', '<extra_id_71>', '<extra_id_70>', '<extra_id_69>', '<extra_id_68>', '<extra_id_67>', '<extra_id_66>', '<extra_id_65>', '<extra_id_64>', '<extra_id_63>', '<extra_id_62>', '<extra_id_61>', '<extra_id_60>', '<extra_id_59>', '<extra_id_58>', '<extra_id_5

AssertionError: 

In [30]:
with tempfile.TemporaryDirectory() as dir_path: 
    model_path = os.path.join(dir_path, 't5_spm.model')
    download(
        url=get_repo_url() + 'tokenizer_test_models/sentencepiece/case_t5/test_t5spm-5f05e7.model',
        path=model_path
    )
    vocab_path = os.path.join(dir_path, 't5_spm_vocab.json')
    download(
        url=get_repo_url() + 'tokenizer_test_models/sentencepiece/case_t5/test_t5spm_vocab-a9d819.json', 
        path=vocab_path
    )
    vocab = (json.load(vocab_path), 
    # gluon = SentencepieceTokenizer(
    #     model_path=model_path, 
    #     vocab=load_vocab(vocab_path)
    # )
    # print(gluon._vocab.special_tokens)
    # print(gluon._vocab['<extra_id_0>'], gluon._vocab['<extra_id_99>'])
    # for token in gluon._vocab.special_tokens:
    #     piece_id = gluon._sp_model.piece_to_id(token)
    #     print(token, piece_id)
    #     if gluon._sp_model.is_unknown(piece_id):
    #         assert gluon._vocab[token] == gluon._sp_model.unk_id()
    # os.remove(model_path)
    # os.remove(vocab_path)

([['▁Hello', ',', '▁', 'y', "'", 'all', '!', '▁How', '▁are', '▁you', '▁VIII', '▁', '😁', '▁', '😁', '▁', '😁', '▁', '?'], ['▁', 'Glu', 'on', 'N', 'LP', '▁is', '▁great', '!', '!!!!!'], ['▁', 'Glu', 'on', 'N', 'LP', '-', 'Am', 'a', 'zon', '-', 'H', 'a', 'i', 'bin', '-', 'Le', 'on', 'ard', '-', 'She', 'ng', '-', 'Sh', 'u', 'a', 'i', '-', 'X', 'ing', 'j', 'i', 'an', '.....', '/', ':', '!', '@', '#', '▁', "'", 'a', 'b', 'c', "'"]], [[(0, 5), (5, 6), (6, 7), (7, 8), (8, 9), (9, 12), (12, 13), (13, 17), (17, 21), (21, 25), (25, 27), (27, 28), (28, 29), (29, 30), (30, 31), (31, 32), (32, 33), (33, 34), (34, 35)], [(0, 0), (0, 3), (3, 5), (5, 6), (6, 8), (8, 11), (11, 17), (17, 18), (18, 23)], [(0, 0), (0, 3), (3, 5), (5, 6), (6, 8), (8, 9), (9, 11), (11, 12), (12, 15), (15, 16), (16, 17), (17, 18), (18, 19), (19, 22), (22, 23), (23, 25), (25, 27), (27, 30), (30, 31), (31, 34), (34, 36), (36, 37), (37, 39), (39, 40), (40, 41), (41, 42), (42, 43), (43, 44), (44, 47), (47, 48), (48, 49), (49, 51), (

In [ ]:
SUBWORD_TEST_SAMPLES = ["Hello, y'all! How are you Ⅷ 😁 😁 😁 ?",
                        'GluonNLP is great！！！!!!',
                        "GluonNLP-Amazon-Haibin-Leonard-Sheng-Shuai-Xingjian...../:!@# 'abc'"]

print(gluon.encode(SUBWORD_TEST_SAMPLES, int))
print(trans(SUBWORD_TEST_SAMPLES))

print(gluon.encode_with_offsets(SUBWORD_TEST_SAMPLES))

ints = gluon.encode(SUBWORD_TEST_SAMPLES, int)
gluon.decode(ints)

In [15]:
import json

In [ ]:
gluon = SentencepieceTokenizer(
    model_path=trans.vocab_file, 
)
vocab = gluon._vocab.to_json()
vocab = json.loads(vocab)
# with open('/home/ubuntu/yongyiw/temp/test_t5spm.json', 'w') as vocab_file: 
#     json.dump(vocab, vocab_file)

In [31]:
def noise_span_to_unique_sentinel(tokens, noise_mask, vocab):
  """Replace each run of consecutive noise tokens with a different sentinel.
  The idea here is to be able to align the dropped spans in the inputs
  with the markers in the targets.
  We want to generate training examples like
  "We hold X to be Y that" -> "X these truths Y self evident Z"
  Sentinels assigned in decreasing order within the sequence starting at
  vocabulary.size - 1.  That is, we appropriate the last tokens in the
  vocabulary for additional use as sentinels.
  TODO(noam): we may want to try enlarging the vocabulary and leaving room
  for the sentinels instead.  However, this requires enlarging the embedding
  tables in the model, so that is a bigger change.
  Args:
    tokens: a 1d integer Tensor
    noise_mask: a boolean Tensor with the same shape as tokens
    vocabulary: a vocabulary.Vocabulary
    seeds: an unused int32 Tensor
  Returns:
    a Tensor with the same shape and dtype as tokens
  """
  vocab_size = vocab
  prev_token_is_noise = tf.pad(noise_mask[:-1], [[1, 0]])

  first_noise_tokens = tf.logical_and(
      noise_mask, tf.logical_not(prev_token_is_noise))
  subsequent_noise_tokens = tf.logical_and(noise_mask, prev_token_is_noise)

  sentinel = vocab_size - tf.cumsum(tf.cast(first_noise_tokens, tokens.dtype))

  tokens = tf.where(first_noise_tokens, sentinel, tokens)
  return tf.boolean_mask(tokens, tf.logical_not(subsequent_noise_tokens))

<tf.Tensor: shape=(7,), dtype=int32, numpy=array([999,   2,   3,   4, 998,   7, 997], dtype=int32)>

In [ ]:
noise_span_to_unique_sentinel(
    tf.constant([1, 2, 3, 4, 5, 6, 7, 8]), 
    tf.constant([True, False, False, False, True, True, False, True]), 
    1000
)

In [11]:
import functools

def _assert_decoder(fn): 
    @functools.wraps(fn)
    def wrapper(self, *args, **kwargs): 
        assert self._is_decoder, '{}() not belongs to an encoder'.format(fn.__name__)
        return fn(self, *args, *kwargs)
    return wrapper

class A(object): 
    def __init__(self, is_decoder): 
        self._is_decoder = is_decoder

    @_assert_decoder
    def test(self): 
        print("Done")
        return 1

AssertionError: test() not belongs to an encoder

In [12]:
Enc = A(False)
Enc.test()

Done


1

In [ ]:
Dec = A(True)
Dec.test()

In [10]:
import mxnet as mx

In [29]:
mx.random.seed(0)

layer = mx.gluon.nn.Dense(10, in_units=5, weight_initializer=mx.initializer.Normal(0.1))
layer.initialize()
layer.weight.data()


[[ 0.22122064  0.07740038  0.10434403  0.11839255  0.18917114]
 [-0.12347414 -0.17710291 -0.04513844  0.05793836 -0.1856082 ]
 [-0.19768797 -0.02080192  0.02444218 -0.00371607 -0.04877499]
 [-0.00226173  0.05746142  0.14661263  0.06862904  0.0354961 ]
 [ 0.10731696  0.01201746 -0.09711102 -0.07756966 -0.07882176]
 [ 0.07417728 -0.1473444  -0.10730928 -0.10424828 -0.1327885 ]
 [-0.14749663 -0.0524142   0.12662557  0.08950642 -0.06015945]
 [ 0.12040559 -0.09712193 -0.05825623  0.03717077  0.09300072]
 [-0.14225756 -0.05176199  0.20088325  0.02863085  0.05604595]
 [ 0.09697597 -0.05285374 -0.188909    0.06547912 -0.04548132]]
<NDArray 10x5 @cpu(0)>

In [31]:
mx.random.seed(0)

layer = mx.gluon.nn.Dense(10, in_units=5, weight_initializer=mx.init.Normal(0.1))
layer.initialize()
layer.weight.data()


[[ 0.22122064  0.07740038  0.10434403  0.11839255  0.18917114]
 [-0.12347414 -0.17710291 -0.04513844  0.05793836 -0.1856082 ]
 [-0.19768797 -0.02080192  0.02444218 -0.00371607 -0.04877499]
 [-0.00226173  0.05746142  0.14661263  0.06862904  0.0354961 ]
 [ 0.10731696  0.01201746 -0.09711102 -0.07756966 -0.07882176]
 [ 0.07417728 -0.1473444  -0.10730928 -0.10424828 -0.1327885 ]
 [-0.14749663 -0.0524142   0.12662557  0.08950642 -0.06015945]
 [ 0.12040559 -0.09712193 -0.05825623  0.03717077  0.09300072]
 [-0.14225756 -0.05176199  0.20088325  0.02863085  0.05604595]
 [ 0.09697597 -0.05285374 -0.188909    0.06547912 -0.04548132]]
<NDArray 10x5 @cpu(0)>

In [40]:
A = {"V1": 8, "V2": 1024, "V3": False}
B = {"V4": 1.0, "V5": True}

In [41]:
def foo(V1=0, V2=0, V3=True, V4=0, V5=False): 
    print(V1, V2, V3, V4, V5)

In [47]:
foo(V5=False, **A, **B)

TypeError: foo() got multiple values for keyword argument 'V5'

In [54]:
t5 = T5Model.from_pretrained('t5-base')

Downloading:   0%|          | 0.00/1.20k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/892M [00:00<?, ?B/s]

In [57]:
t5.cfg

ModuleAttributeError: 'T5Model' object has no attribute 'cfg'

In [93]:
from mxnet import np, npx

In [110]:
A = np.array([[1, 2, 2, 3, 3, 4], [3, 4, 4, 5, 5, 6], [4, 5, 5, 6, 6, 7]])

In [111]:
A = np.expand_dims(A, 1)

In [118]:
npx.reshape(A, (-5, -1)).shape

(3, 6)

In [119]:
from gluonnlp.attention_cell import (
    gen_self_attn_mask, gen_mem_attn_mask, MultiHeadAttentionCell, RelAttentionScoreCell
)

In [133]:
A = np.array([[[1, 2, 2, 2], [3, 3, 4, 3]], [[3, 4, 4, 4], [5, 5, 6, 5]], [[4, 5, 5, 5], [6, 6, 7, 6]]])
A.shape

(3, 2, 4)

In [134]:
mem = A
mem_valid_length = np.array([1, 0, 1])
data = np.array([[0]])

In [135]:
gen_mem_attn_mask(mem, mem_valid_length, data)

array([[[ True, False]],

       [[False, False]],

       [[ True, False]]])

In [163]:
time_steps = npx.arange_like(mem, axis=1)  # (mem_length,)
np.reshape(time_steps, (1, 1, -1)) < np.reshape(mem_valid_length, (-1, 1, 1))

array([[[ True, False]],

       [[False, False]],

       [[ True, False]]])

In [12]:
A = np.array([[1, 2, 2, 2], [3, 3, 4, 3], [3, 4, 4, 4], [5, 5, 6, 5], [4, 5, 5, 5], [6, 6, 7, 6]])
A.shape

(6, 4)

In [17]:
B = np.array([[1, 2, 3], [99, 98, 97]])
B.shape

(2, 3)

In [19]:
np.expand_dims(B, 1).broadcast_to((2, 5, 3)).reshape(10, 3)

array([[ 1.,  2.,  3.],
       [ 1.,  2.,  3.],
       [ 1.,  2.,  3.],
       [ 1.,  2.,  3.],
       [ 1.,  2.,  3.],
       [99., 98., 97.],
       [99., 98., 97.],
       [99., 98., 97.],
       [99., 98., 97.],
       [99., 98., 97.]])

In [20]:
A = np.zeros((4 * 32, 32000))

In [59]:
B = np.zeros((12, 4))
npx.reshape(B, (-6, 2, 4, -1)).shape

MXNetError: Traceback (most recent call last):
  File "../src/operator/numpy/np_matrix_op.cc", line 283
MXNetError: Check failed: d1 * d2 == static_cast<dim_t>(d0) || static_cast<dim_t>(d0) == dim_t(-1): Split dims 2, 4 do not divide original dim 12

In [196]:
pos = np.zeros((3,), dtype=np.int32)

In [205]:
np.take(A, np.array([0, 5, 10, 15]))

array([1., 3., 4., 5.])

In [244]:
np.expand_dims(np.take(A, np.array([0, 1, 2, 3]), axis=0), axis=1)

array([[[1., 2., 2., 2.]],

       [[3., 3., 4., 3.]],

       [[3., 4., 4., 4.]],

       [[5., 5., 6., 5.]]])

In [239]:
A

array([[1., 2., 2., 2.],
       [3., 3., 4., 3.],
       [3., 4., 4., 4.],
       [5., 5., 6., 5.],
       [4., 5., 5., 5.],
       [6., 6., 7., 6.]])

In [233]:
npx.pick(A, np.array([3, 1, 2, 0]), axis=0)

array([5., 3., 4., 2.])

In [249]:
np.min(A).item()

1.0

In [281]:
A = nn.Embedding(10, 50)
A.collect_params()

{'weight': Parameter (shape=(10, 50), dtype=float32)}

In [285]:
type(A.collect_params())

dict

In [286]:
A = nn.Embedding(
    input_dim=1024, 
    output_dim=512
)

In [287]:
A.weight.shape

(1024, 512)

In [288]:
B = nn.Dense(
    units=1024, 
    in_units=512, 
    use_bias=False
)

In [289]:
B.weight.shape

(1024, 512)

In [11]:
import mxnet as mx
from mxnet import np, npx

mx.npx.set_np()

A = np.zeros(shape=(1, 0, 12, 64), ctx=mx.gpu(), dtype='float32')
npx.reshape(A, (-2, -2, -5))

array([], shape=(1, 0, 768), ctx=gpu(0))