In [2]:
from transformers import T5Tokenizer
from gluonnlp.data.tokenizers import SentencepieceTokenizer
from gluonnlp.data.vocab import Vocab

In [3]:
trans = T5Tokenizer.from_pretrained("t5-base")

In [6]:
# extra_ids = 100
# special_tokens = {'extra_{}_token'.format(i): '<extra_id_{}>'.format(i) for i in range(extra_ids)}
# special_tokens['eos_token'] = '</s>'
# special_tokens['unk_token'] = '<unk>'
# special_tokens['pad_token'] = '<pad>'
# gluon = SentencepieceTokenizer(
#     vocab=Vocab(trans.get_vocab(), **special_tokens)
# )

In [4]:
extra_ids = 100
do_lower = False

additional_special_tokens = {'extra{}_token'.format(i): '<extra_id_{}>'.format(i) for i in range(extra_ids - 1, -1, -1)}
tokenizer = SentencepieceTokenizer(
    model_path=trans.vocab_file,
    lowercase=do_lower, 
    **additional_special_tokens
)

In [17]:
import tempfile
import os

from gluonnlp.base import get_repo_url
from gluonnlp.data import load_vocab
from gluonnlp.utils.misc import download

100%|██████████| 792k/792k [00:00<00:00, 11.7MiB/s]
100%|██████████| 476k/476k [00:00<00:00, 8.02MiB/s]Downloading /tmp/tmpptcvki94/t5_spm.model from s3://gluonnlp-numpy-data/tokenizer_test_models/sentencepiece/case_t5/test_t5spm-5f05e7.model...

['<pad>', '</s>', '<unk>', '<extra_id_99>', '<extra_id_98>', '<extra_id_97>', '<extra_id_96>', '<extra_id_95>', '<extra_id_94>', '<extra_id_93>', '<extra_id_92>', '<extra_id_91>', '<extra_id_90>', '<extra_id_89>', '<extra_id_88>', '<extra_id_87>', '<extra_id_86>', '<extra_id_85>', '<extra_id_84>', '<extra_id_83>', '<extra_id_82>', '<extra_id_81>', '<extra_id_80>', '<extra_id_79>', '<extra_id_78>', '<extra_id_77>', '<extra_id_76>', '<extra_id_75>', '<extra_id_74>', '<extra_id_73>', '<extra_id_72>', '<extra_id_71>', '<extra_id_70>', '<extra_id_69>', '<extra_id_68>', '<extra_id_67>', '<extra_id_66>', '<extra_id_65>', '<extra_id_64>', '<extra_id_63>', '<extra_id_62>', '<extra_id_61>', '<extra_id_60>', '<extra_id_59>', '<extra_id_58>', '<extra_id_5

AssertionError: 

In [30]:
with tempfile.TemporaryDirectory() as dir_path: 
    model_path = os.path.join(dir_path, 't5_spm.model')
    download(
        url=get_repo_url() + 'tokenizer_test_models/sentencepiece/case_t5/test_t5spm-5f05e7.model',
        path=model_path
    )
    vocab_path = os.path.join(dir_path, 't5_spm_vocab.json')
    download(
        url=get_repo_url() + 'tokenizer_test_models/sentencepiece/case_t5/test_t5spm_vocab-a9d819.json', 
        path=vocab_path
    )
    vocab = (json.load(vocab_path), 
    # gluon = SentencepieceTokenizer(
    #     model_path=model_path, 
    #     vocab=load_vocab(vocab_path)
    # )
    # print(gluon._vocab.special_tokens)
    # print(gluon._vocab['<extra_id_0>'], gluon._vocab['<extra_id_99>'])
    # for token in gluon._vocab.special_tokens:
    #     piece_id = gluon._sp_model.piece_to_id(token)
    #     print(token, piece_id)
    #     if gluon._sp_model.is_unknown(piece_id):
    #         assert gluon._vocab[token] == gluon._sp_model.unk_id()
    # os.remove(model_path)
    # os.remove(vocab_path)

([['▁Hello', ',', '▁', 'y', "'", 'all', '!', '▁How', '▁are', '▁you', '▁VIII', '▁', '😁', '▁', '😁', '▁', '😁', '▁', '?'], ['▁', 'Glu', 'on', 'N', 'LP', '▁is', '▁great', '!', '!!!!!'], ['▁', 'Glu', 'on', 'N', 'LP', '-', 'Am', 'a', 'zon', '-', 'H', 'a', 'i', 'bin', '-', 'Le', 'on', 'ard', '-', 'She', 'ng', '-', 'Sh', 'u', 'a', 'i', '-', 'X', 'ing', 'j', 'i', 'an', '.....', '/', ':', '!', '@', '#', '▁', "'", 'a', 'b', 'c', "'"]], [[(0, 5), (5, 6), (6, 7), (7, 8), (8, 9), (9, 12), (12, 13), (13, 17), (17, 21), (21, 25), (25, 27), (27, 28), (28, 29), (29, 30), (30, 31), (31, 32), (32, 33), (33, 34), (34, 35)], [(0, 0), (0, 3), (3, 5), (5, 6), (6, 8), (8, 11), (11, 17), (17, 18), (18, 23)], [(0, 0), (0, 3), (3, 5), (5, 6), (6, 8), (8, 9), (9, 11), (11, 12), (12, 15), (15, 16), (16, 17), (17, 18), (18, 19), (19, 22), (22, 23), (23, 25), (25, 27), (27, 30), (30, 31), (31, 34), (34, 36), (36, 37), (37, 39), (39, 40), (40, 41), (41, 42), (42, 43), (43, 44), (44, 47), (47, 48), (48, 49), (49, 51), (

In [ ]:
SUBWORD_TEST_SAMPLES = ["Hello, y'all! How are you Ⅷ 😁 😁 😁 ?",
                        'GluonNLP is great！！！!!!',
                        "GluonNLP-Amazon-Haibin-Leonard-Sheng-Shuai-Xingjian...../:!@# 'abc'"]

print(gluon.encode(SUBWORD_TEST_SAMPLES, int))
print(trans(SUBWORD_TEST_SAMPLES))

print(gluon.encode_with_offsets(SUBWORD_TEST_SAMPLES))

ints = gluon.encode(SUBWORD_TEST_SAMPLES, int)
gluon.decode(ints)

In [15]:
import json

In [ ]:
gluon = SentencepieceTokenizer(
    model_path=trans.vocab_file, 
)
vocab = gluon._vocab.to_json()
vocab = json.loads(vocab)
# with open('/home/ubuntu/yongyiw/temp/test_t5spm.json', 'w') as vocab_file: 
#     json.dump(vocab, vocab_file)

In [31]:
def noise_span_to_unique_sentinel(tokens, noise_mask, vocab):
  """Replace each run of consecutive noise tokens with a different sentinel.
  The idea here is to be able to align the dropped spans in the inputs
  with the markers in the targets.
  We want to generate training examples like
  "We hold X to be Y that" -> "X these truths Y self evident Z"
  Sentinels assigned in decreasing order within the sequence starting at
  vocabulary.size - 1.  That is, we appropriate the last tokens in the
  vocabulary for additional use as sentinels.
  TODO(noam): we may want to try enlarging the vocabulary and leaving room
  for the sentinels instead.  However, this requires enlarging the embedding
  tables in the model, so that is a bigger change.
  Args:
    tokens: a 1d integer Tensor
    noise_mask: a boolean Tensor with the same shape as tokens
    vocabulary: a vocabulary.Vocabulary
    seeds: an unused int32 Tensor
  Returns:
    a Tensor with the same shape and dtype as tokens
  """
  vocab_size = vocab
  prev_token_is_noise = tf.pad(noise_mask[:-1], [[1, 0]])

  first_noise_tokens = tf.logical_and(
      noise_mask, tf.logical_not(prev_token_is_noise))
  subsequent_noise_tokens = tf.logical_and(noise_mask, prev_token_is_noise)

  sentinel = vocab_size - tf.cumsum(tf.cast(first_noise_tokens, tokens.dtype))

  tokens = tf.where(first_noise_tokens, sentinel, tokens)
  return tf.boolean_mask(tokens, tf.logical_not(subsequent_noise_tokens))

<tf.Tensor: shape=(7,), dtype=int32, numpy=array([999,   2,   3,   4, 998,   7, 997], dtype=int32)>

In [ ]:
noise_span_to_unique_sentinel(
    tf.constant([1, 2, 3, 4, 5, 6, 7, 8]), 
    tf.constant([True, False, False, False, True, True, False, True]), 
    1000
)

In [11]:
import functools

def _assert_decoder(fn): 
    @functools.wraps(fn)
    def wrapper(self, *args, **kwargs): 
        assert self._is_decoder, '{}() not belongs to an encoder'.format(fn.__name__)
        return fn(self, *args, *kwargs)
    return wrapper

class A(object): 
    def __init__(self, is_decoder): 
        self._is_decoder = is_decoder

    @_assert_decoder
    def test(self): 
        print("Done")
        return 1

AssertionError: test() not belongs to an encoder

In [12]:
Enc = A(False)
Enc.test()

Done


1

In [ ]:
Dec = A(True)
Dec.test()

In [10]:
import mxnet as mx

In [29]:
mx.random.seed(0)

layer = mx.gluon.nn.Dense(10, in_units=5, weight_initializer=mx.initializer.Normal(0.1))
layer.initialize()
layer.weight.data()


[[ 0.22122064  0.07740038  0.10434403  0.11839255  0.18917114]
 [-0.12347414 -0.17710291 -0.04513844  0.05793836 -0.1856082 ]
 [-0.19768797 -0.02080192  0.02444218 -0.00371607 -0.04877499]
 [-0.00226173  0.05746142  0.14661263  0.06862904  0.0354961 ]
 [ 0.10731696  0.01201746 -0.09711102 -0.07756966 -0.07882176]
 [ 0.07417728 -0.1473444  -0.10730928 -0.10424828 -0.1327885 ]
 [-0.14749663 -0.0524142   0.12662557  0.08950642 -0.06015945]
 [ 0.12040559 -0.09712193 -0.05825623  0.03717077  0.09300072]
 [-0.14225756 -0.05176199  0.20088325  0.02863085  0.05604595]
 [ 0.09697597 -0.05285374 -0.188909    0.06547912 -0.04548132]]
<NDArray 10x5 @cpu(0)>

In [31]:
mx.random.seed(0)

layer = mx.gluon.nn.Dense(10, in_units=5, weight_initializer=mx.init.Normal(0.1))
layer.initialize()
layer.weight.data()


[[ 0.22122064  0.07740038  0.10434403  0.11839255  0.18917114]
 [-0.12347414 -0.17710291 -0.04513844  0.05793836 -0.1856082 ]
 [-0.19768797 -0.02080192  0.02444218 -0.00371607 -0.04877499]
 [-0.00226173  0.05746142  0.14661263  0.06862904  0.0354961 ]
 [ 0.10731696  0.01201746 -0.09711102 -0.07756966 -0.07882176]
 [ 0.07417728 -0.1473444  -0.10730928 -0.10424828 -0.1327885 ]
 [-0.14749663 -0.0524142   0.12662557  0.08950642 -0.06015945]
 [ 0.12040559 -0.09712193 -0.05825623  0.03717077  0.09300072]
 [-0.14225756 -0.05176199  0.20088325  0.02863085  0.05604595]
 [ 0.09697597 -0.05285374 -0.188909    0.06547912 -0.04548132]]
<NDArray 10x5 @cpu(0)>

In [40]:
A = {"V1": 8, "V2": 1024, "V3": False}
B = {"V4": 1.0, "V5": True}

In [41]:
def foo(V1=0, V2=0, V3=True, V4=0, V5=False): 
    print(V1, V2, V3, V4, V5)

In [47]:
foo(V5=False, **A, **B)

TypeError: foo() got multiple values for keyword argument 'V5'